apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: MythicalEKS
  region: eu-west-1

vpc:
  id: "your VPC ID"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.0.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      eu-west-1a:
        id: "your subnet id"
        cidr: "10.0.2.0/24" # (optional, must match CIDR used by the given subnet)

      eu-west-1b:
        id: "your subnet id" 
        cidr: "10.0.3.0/24"  # (optional, must match CIDR used by the given subnet)

managedNodeGroups:
  - name: Mythicalmanaged-web
    instanceType: m5.large
    minSize: 2
    desiredCapacity: 3
    maxSize: 4
    availabilityZones: ["eu-west-1a", "eu-west-1b"]
    privateNetworking: true
  #  securityGroups:
  #    attachIDs: ["sg-1", "sg-2"]
   # ssh:
    #  allow: true
   #   publicKeyPath: ~/.ssh/ec2_id_rsa.pub
      # new feature for restricting SSH access to certain AWS security group IDs
   #   sourceSecurityGroupIds: ["sg-00241fbb12c607007"]
    labels: {role: web}
    tags:
      nodegroup-role: web
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
