apiVersion: v1
kind: Service
metadata:
  name: "service-mythicalapi"
  namespace: "mythical-api"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: "mythical-api"
